### PR TITLE
remove 'schnitzel' as it also matches @schnitzel

### PR DESCRIPTION
**Pull request by Schnitzel**
and that's actually super annoying if your twitter username is "@schnitzel" or people are tweeting at you and get their tweets faved or replied, even though the topic is not about schnitzel :)

### CODE REVIEW

**Comment by Schnitzel** [comment]
would make my life on twitter easier ;)

**Comment by mfa** [comment]
changed in a different way. but should work. see ec0c868aa7ab29427c6b70e1eee114e2af2b94c7

**Comment by Schnitzel** [comment]
@mfa 
he still replies to me, as the fix just checks for the tweet text, but it matches also the username tweeting:
https://twitter.com/SchnitzelFollow/status/564060727640862720

Thanks for fixing :)

**Comment by mfa** [comment]
I blacklisted your useraccount. hope that works.
see 91e7318f8de8785f3a39b6bb5b2a26341892cb13

**Comment by Schnitzel** [comment]
thanks! let's see how this works :)

**Pull request merged**
